#!/usr/bin/with-contenv sh

. "/usr/bin/variables"

echo "Creating directories..."

if [ ! -d "${MOUNT_DIR}" ]; then
    mkdir -p "${MOUNT_DIR}"
fi
if [ ! -d "${PLEXDRIVE_MOUNT}" ]; then
    mkdir -p "${PLEXDRIVE_MOUNT}"
fi
if [ ! -d "${UPLOAD_QUEUE}" ]; then
    mkdir -p "${UPLOAD_QUEUE}"
fi
if [ ! -d "${RCLONE_MOUNT}" ]; then
    mkdir -p "${RCLONE_MOUNT}"
fi

if [ ! -d "${DB_DIR}" ]; then
    mkdir -p "${DB_DIR}"
fi
if [ ! -d "${LOG_DIR}" ]; then
    mkdir -p "${LOG_DIR}"
fi
