#!/usr/bin/with-contenv sh

. "/usr/bin/variables"

echo "Creating user..."

usermod -o -u "$PUID" abc
groupmod -o -g "$PGID" abc

echo "Fixing permissions..."

chmod a+r /etc/fuse.conf

chmod -R 777 \
    /var/lock \
    $CONFIG_ROOT

chown -R abc:abc \
    $CONFIG_ROOT \
    /usr/bin/*