name: Pubish Docker image
on:
    push:
        branches:
            - master
    workflow_dispatch:
        branches:
            - master
env:
    IMAGE_NAME: cloudmount
jobs:
    push_to_registries:
        name: Push Docker image
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
              with:
                  submodules: true
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Push to Docker Hub
              uses: docker/build-push-action@v2
              with:
                  context: .
                  pull: true
                  push: true
                  tags: drkno/cloudmount:latest
